[package]
name = "tanban"
version = "0.1.0"
edition = "2021"
authors = ["Fitzypop <fitzypop@pm.me>"]
license-file = "LICENSE"
description = "TUI Kanban Board"
repository = "https://github.com/fitzypop/tanban"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19.0"
